import { createLabelGetter } from "./shared";

export const PERMISSION = {
  ORG_MANAGE: "org.manage",
  MEMBER_INVITE: "member.invite",
  ANNOUNCEMENT_MANAGE: "announcement.manage",
  PROJECT_CREATE: "project.create",
  PROJECT_UPDATE: "project.update",
  PROJECT_DELETE: "project.delete",
  ISSUE_KANBAN_CREATE: "issue.kanban.create",
  ISSUE_KANBAN_UPDATE: "issue.kanban.update",
  ISSUE_KANBAN_DELETE: "issue.kanban.delete",
  ISSUE_EXPENSES_CLAIM_CREATE: "issue.expenses_claim.create",
  ISSUE_EXPENSES_CLAIM_EDIT: "issue.expenses_claim.edit",
  ISSUE_EXPENSES_CLAIM_UPDATE: "issue.expenses_claim.update",
  ISSUE_EXPENSES_CLAIM_DELETE: "issue.expenses_claim.delete",
  EXPENSES_CLAIM_CATEGORY_MANAGE: "expenses_claim.category.manage",
  ISSUE_VENUE_BOOKING_CREATE: "issue.venue_booking.create",
  ISSUE_VENUE_BOOKING_EDIT: "issue.venue_booking.edit",
  ISSUE_VENUE_BOOKING_UPDATE: "issue.venue_booking.update",
  ISSUE_VENUE_BOOKING_DELETE: "issue.venue_booking.delete",
  ISSUE_ASSET_BOOKING_CREATE: "issue.asset_booking.create",
  ISSUE_ASSET_BOOKING_EDIT: "issue.asset_booking.edit",
  ISSUE_ASSET_BOOKING_UPDATE: "issue.asset_booking.update",
  ISSUE_ASSET_BOOKING_DELETE: "issue.asset_booking.delete",
  ACCOUNTING_ACCOUNT_MANAGE: "accounting.account.manage",
  ACCOUNTING_LEDGER_READ: "accounting.ledger.read",
  ACCOUNTING_JOURNAL_POST: "accounting.journal.post",
  ACCOUNTING_JOURNAL_REVERSE: "accounting.journal.reverse",
  ACCOUNTING_PERIOD_CLOSE: "accounting.period.close",
  ACCOUNTING_EXCHANGE_RATE_MANAGE: "accounting.exchange_rate.manage",
  ACCOUNTING_INVOICE_MANAGE: "accounting.invoice.manage",
  ACCOUNTING_INVOICE_ISSUE: "accounting.invoice.issue",
  ACCOUNTING_BANK_RECONCILE: "accounting.bank.reconcile",
  ACCOUNTING_CLAIM_RATE_MANAGE: "accounting.claim_rate.manage",
} as const;

export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION];

export const PERMISSION_LABEL: Record<Permission, string> = {
  [PERMISSION.ORG_MANAGE]: "Manage Organization",
  [PERMISSION.MEMBER_INVITE]: "Invite Members",
  [PERMISSION.ANNOUNCEMENT_MANAGE]: "Manage Announcements",
  [PERMISSION.PROJECT_CREATE]: "Create Projects",
  [PERMISSION.PROJECT_UPDATE]: "Update Projects",
  [PERMISSION.PROJECT_DELETE]: "Delete Projects",
  [PERMISSION.ISSUE_KANBAN_CREATE]: "Create Kanban Issues",
  [PERMISSION.ISSUE_KANBAN_UPDATE]: "Update Kanban Issues",
  [PERMISSION.ISSUE_KANBAN_DELETE]: "Delete Kanban Issues",
  [PERMISSION.ISSUE_EXPENSES_CLAIM_CREATE]: "Create Expense Claims",
  [PERMISSION.ISSUE_EXPENSES_CLAIM_EDIT]: "Edit Expense Claims",
  [PERMISSION.ISSUE_EXPENSES_CLAIM_UPDATE]: "Update Expense Claims",
  [PERMISSION.ISSUE_EXPENSES_CLAIM_DELETE]: "Delete Expense Claims",
  [PERMISSION.EXPENSES_CLAIM_CATEGORY_MANAGE]:
    "Manage Expense Claim Categories",
  [PERMISSION.ISSUE_VENUE_BOOKING_CREATE]: "Create Venue Bookings",
  [PERMISSION.ISSUE_VENUE_BOOKING_EDIT]: "Edit Venue Bookings",
  [PERMISSION.ISSUE_VENUE_BOOKING_UPDATE]: "Update Venue Bookings",
  [PERMISSION.ISSUE_VENUE_BOOKING_DELETE]: "Delete Venue Bookings",
  [PERMISSION.ISSUE_ASSET_BOOKING_CREATE]: "Create Asset Bookings",
  [PERMISSION.ISSUE_ASSET_BOOKING_EDIT]: "Edit Asset Bookings",
  [PERMISSION.ISSUE_ASSET_BOOKING_UPDATE]: "Update Asset Bookings",
  [PERMISSION.ISSUE_ASSET_BOOKING_DELETE]: "Delete Asset Bookings",
  [PERMISSION.ACCOUNTING_ACCOUNT_MANAGE]: "Manage Chart of Accounts",
  [PERMISSION.ACCOUNTING_LEDGER_READ]: "View Ledger",
  [PERMISSION.ACCOUNTING_JOURNAL_POST]: "Post Journal Entries",
  [PERMISSION.ACCOUNTING_JOURNAL_REVERSE]: "Reverse Journal Entries",
  [PERMISSION.ACCOUNTING_PERIOD_CLOSE]: "Close Fiscal Periods",
  [PERMISSION.ACCOUNTING_EXCHANGE_RATE_MANAGE]: "Manage Exchange Rates",
  [PERMISSION.ACCOUNTING_INVOICE_MANAGE]: "Manage Invoices",
  [PERMISSION.ACCOUNTING_INVOICE_ISSUE]: "Issue Invoices",
  [PERMISSION.ACCOUNTING_BANK_RECONCILE]: "Reconcile Bank Accounts",
  [PERMISSION.ACCOUNTING_CLAIM_RATE_MANAGE]: "Manage Claim Rates",
};

export const getPermissionLabel =
  createLabelGetter<Permission>(PERMISSION_LABEL);
